# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

 gem 'benchmark-ips'
 gem 'memory_profiler'
 gem 'benchmark_driver'
